allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@angular/animations@21.2.21'
  - '@angular/common@21.2.21'
  - '@angular/compiler-cli@21.2.21'
  - '@angular/compiler@21.2.21'
  - '@angular/core@21.2.21'
  - '@angular/forms@21.2.21'
  - '@angular/platform-browser-dynamic@21.2.21'
  - '@angular/platform-browser@21.2.21'
  - '@angular/router@21.2.21'
